### ISSUE TITLE
After Installing BurpExtender.java But not showing.

### ISSUE THREAD

**Issue by xniravx** [tangxiaofeng7/BurpLog4j2Scan#3]
Dear Sir,

After installing BurpExtender.java its shows shiroscan tab 

https://i.imgur.com/n4ywywV.png

but not showing this: 

Extensions->BurpLog4j2-scan->Send to Log4jScan

https://i.imgur.com/xzzGW8e.png.

How you tell how to install this BurpLog4j2Scan.?

Thanks

**Comment by tangxiaofeng7** [comment]
Hi, please make sure the download url is https://github.com/tangxiaofeng7/BurpLog4j2Scan/releases/download/v1.0/BurpLog4j2Scan-1.0-SNAPSHOT.jar

**Comment by xniravx** [comment]
yes, its works. Thanks, dear.😊😉
